### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by SPAHI4** [meteorwebcomponents/ecmascript#1]
I added `mwc:ecmascript` package but nothing happens.
Babel for meteor works perfect.
Why could this happen?

**Comment by aruntk** [comment]
@SPAHI4 This extension compiles the script sections of the files listed in the config.mwc.json. To check if its working open the file `public/mwc_compiler.html` and search for `<!-- ECMA COMPILED -->`. mwc:compiler compiles all the files in your polymer root folder. So meteor babel wont work on them. Moreover meteor babel only compiles js/jsx files while in most polymer elements script is written inside the html file itself. mwc:ecmascript works in this scenario.

**Comment by SPAHI4** [comment]
@arunhedcet i did not find `<!-- ECMA COMPILED -->` in `public/mwc_compiler.html`
Files that need compile listed in the import section in compile.mwc.json

**Comment by aruntk** [comment]
Which version of `mwc:ecmascript` are you using? Do you have `mwc:extensions` package installed? Try `meteor update`. If that doesnt work try deleting the existing `public/mwc_compiler.html` file.

**Comment by SPAHI4** [comment]
No, `mwc:extensions` package has not been installed. 
I installed mwc:extensions then run `meteor update` and got a message

```
 Errors while upgrading packages:

While checking for mwc:ecmascript@0.0.6:
error: No compatible binary build found for this package. Contact the package author and ask them to publish it for your platform.
```

same on windows and linux x64

**Comment by aruntk** [comment]
This issue occured when I published the version 0.0.6 https://github.com/meteor/meteor/issues/3977.

Try adding `mwc:compiler@1.1.8` , `mwc:extensions@0.0.1` , `mwc:ecmascript@0.0.3` . Thats should solve the issue or wait for me to figure out why the above issue occurs.

**Comment by aruntk** [comment]
@SPAHI4 The error is related to https://stackoverflow.com/questions/35628681/meteor-weak-dependency-not-working . Please wait until I get a solution for this issue.

**Comment by SPAHI4** [comment]
latest version (1.0.5) and other packages are up-to-date, still no result

**Comment by aruntk** [comment]
@SPAHI4 As I've said there is an issue with meteor weak dependencies. https://github.com/meteor/meteor/issues/6344 .

**Comment by aruntk** [comment]
@SPAHI4 with the latest compiler version 1.1.43 extensions are enabled and are working fine. Refer https://github.com/meteorwebcomponents/extensions and https://github.com/meteorwebcomponents/compiler readme files

**Comment by SPAHI4** [comment]
Now works fine. Nice job!

**Comment by aruntk** [comment]
@SPAHI4 thanks dude. Remember to add mdg `es5-shim` for older browser support and `ecmascript` packages for folders other than the polymer root folder and mwc.json file.
